"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

#generating Fibonacci sequence --- last terms exceed 4 million
terms = [1, 2]
while terms[-1] < 4000000:
	terms.append(terms[-1]+terms[-2])
	
#summation of even terms

evensum=0
for i in terms:
	if i < 4000000 and i % 2==0:
		evensum = evensum+i
print evensum